---
- name: install barman
  yum:
    name: barman
    state: present

- name: store connection info for barman
  template:
    src: templates/.pgpass
    dest: /var/lib/barman/.pgpass
    mode: 0600
    owner: barman
    group: barman

- name: copy backup configuration
  template:
    src: templates/barman.conf
    dest: /etc/barman.d/master.local.conf
    mode: 0644

- name: create replication slot
  shell: |
    barman receive-wall --create-slot {{ master_hostname }}
    touch /var/lib/barman/slot-created
  args:
    creates: /var/lib/barman/slot-created
