---
- name: download barman repo file
  get_url:
    url: https://dl.2ndquadrant.com/default/release/get/11/rpm
    dest: /tmp/install-barman-repo.sh
    mode: 0550

- name: setup barman official repo
  command: /tmp/install-barman-repo.sh
  args:
    creates: /etc/yum.repos.d/2ndquadrant-dl-default-release-pg11.repo

- name: install barman
  yum:
    name: barman
    state: present

- name: store connection info for barman
  template:
    src: templates/.pgpass
    dest: /var/lib/barman/.pgpass
    mode: 0600
    owner: barman
    group: barman

- name: copy backup configuration
  template:
    src: templates/pg.conf
    dest: /etc/barman.d/master.local.conf
    mode: 0644
