---
- name: Add records to /etc/hosts
  hosts: all
  become: True
  gather_facts: False
  vars_files:
    - global_vars.yml
  tasks:
    - name: setup dns resolution
      include_role:
        name: add-entry-to-hosts
      vars:
        ip: '{{ item.ip }}'
        dns: '{{ item.hostname }}'
      loop: '{{ nodes }}'

- name: setup nodes
  hosts: all
  become: True
  gather_facts: True
  vars_files:
    - global_vars.yml
  roles:
    - postgres11-repo
    - postgres11-server
    - etcd
