---
- name: Add records to /etc/hosts
  hosts: all
  become: True
  gather_facts: False
  vars_files:
    - global_vars.yml
  roles:
    - role: add-entry-to-hosts
      ip: '{{ node1_ip }}'
      dns: '{{ node1_hostname }}'
    - role: add-entry-to-hosts
      ip: '{{ node2_ip }}'
      dns: '{{ node2_hostname }}'
    - role: add-entry-to-hosts
      ip: '{{ node3_ip }}'
      dns: '{{ node3_hostname }}'

- name: setup nodes
  hosts: all
  become: True
  gather_facts: False
  vars_files:
    - global_vars.yml
  roles:
    - postgres11-repo
    - postgres11-server
