---
- name: install percona server dependencies
  yum:
    name:
      - https://repo.percona.com/yum/percona-release-latest.noarch.rpm
      - http://repo.percona.com/centos/7/RPMS/x86_64/Percona-Server-selinux-56-5.6.42-rel84.2.el7.noarch.rpm
    state: present

- name: install percona server
  yum:
    name: Percona-Server-server-57
    state: present
  notify: restart mysql

- name: copy config files
  copy:
    src: files/conf.d/
    dest: /etc/my.cnf.d/conf.d/
  notify: restart mysql
