---
- name: install percona server dependencies
  yum:
    name:
      - https://repo.percona.com/yum/percona-release-latest.noarch.rpm
      - http://repo.percona.com/centos/7/RPMS/x86_64/Percona-Server-selinux-56-5.6.42-rel84.2.el7.noarch.rpm
    state: present

- name: install percona server
  yum:
    name: Percona-Server-server-57
    state: present

- name: copy config files
  copy:
    src: files/conf.d/
    dest: /etc/my.cnf.d/

- name: restart mysql
  systemd:
    name: mysql.service
    state: started
    enabled: yes

- name: get current mysql password
  shell: grep 'A temporary password is generated' /var/log/mysqld.log | awk '{print $11}' | head -1
  register: generated_password

- name: update mysql password
  shell: |
    mysql --connect-expired-password -uroot -p'{{ generated_password.stdout }}' -e 'ALTER USER USER() IDENTIFIED BY "{{ mysql_password }}"'
    sed -i '/A temporary password is generated/d' /var/log/mysqld.log
  when: generated_password.stdout


