---
- name: install epel
  yum:
    name: epel-release
    state: present
- name: install packages for monitoring and troubleshooting
  yum:
    name:
      - iotop
      - sysstat
      - strace
      - atop
    state: present
- name: copy perfomance tuning configuration files
  copy:
    src: '{{ item.src }}'
    dest: '{{ item.dest }}'
    owner: root
    group: root
    mode: 0644
  with_items:
    - { src: 'files/etc/sysctl.conf', dest: '/etc/sysctl.conf' }
    - { src: 'files/etc/security/limits.conf', dest: '/etc/security/limits.conf' }
- name: install nginx
  yum:
    name: nginx
    state: present
  notify: restart nginx
