---
- name: install epel
  yum:
    name: epel-release
    state: present
- name: install packages for monitoring and troubleshooting
  yum:
    name: 
      - iotop
      - sysstat
      - strace
      - atop
    state: present
- name: install nginx
  yum:
    name: nginx
    state: present
  notify: restart nginx
