---
- name: Add records to /etc/hosts
  hosts: all
  become: True
  gather_facts: False
  vars_files:
    - global_vars.yml
  roles:
    - role: add-entry-to-hosts
      ip: '{{ master_ip }}'
      dns: '{{ master_hostname }}'
    - role: add-entry-to-hosts
      ip: '{{ slave_ip }}'
      dns: '{{ slave_hostname }}'
    - role: add-entry-to-hosts
      ip: '{{ backup_ip }}'
      dns: '{{ backup_hostname }}'

- name: setup master
  hosts: master
  become: True
  gather_facts: False
  vars_files:
    - global_vars.yml
  roles:
    - postgresql-server

# - name: setup slave
#   hosts: slave
#   become: True
#   gather_facts: False
#   roles:
#     - postgresql-server

- name: setup backup server
  hosts: backup
  become: True
  gather_facts: False
  vars_files:
    - global_vars.yml
  roles:
    - epel
    - barman
