---
- name: Add records to /etc/hosts
  hosts: all
  become: True
  gather_facts: False
  roles:
    - role: add-entry-to-hosts
      ip: 10.0.10.2
      dns: master
    - role: add-entry-to-hosts
      ip: 10.0.10.3
      dns: slave

- name: setup master
  hosts: master
  become: True
  gather_facts: False
  roles:
    - role: postgresql-server
