---
- name: download sources
  get_url:
    dest: /tmp/prometheus.tar.gz
    url: https://github.com/prometheus/prometheus/releases/download/v{{ prometheus_version }}/prometheus-{{ prometheus_version }}.linux-amd64.tar.gz

- set_fact:
    src_path: /tmp/prometheus-{{ prometheus_version }}.linux-amd64

- name: unarchive sources
  unarchive:
    src: /tmp/prometheus.tar.gz
    dest: /tmp
    remote_src: yes

- name: Move exec file to /usr/bin
  copy:
      dest: /usr/bin/prometheus
      src: "{{ src_path }}/prometheus"
      remote_src: yes

- name: Copy systemd-service unit file
  copy:
      dest: /etc/systemd/system/prometheus.service
      src: files/prometheus.service
