---
- name: configure rsyslog to send critical errors to remote server
  blockinfile:
      path: /etc/rsyslog.conf
      marker: "# {mark} ANSIBLE MANAGED BLOCK: remote logging"
      content: |
        # ### begin forwarding rule ###
        *.crit @{{ server_name }}:514
        # ### end of the forwarding rule ###
  notify: restart rsyslog

- name: configure nginx send all access logs to remote host
  lineinfile:
    path: /etc/nginx/nginx.conf
    state: present
    regexp: 'access_log  /var/log/nginx/access.log  main;'
    line: '    access_log syslog:server={{ server_name }},facility=local7,tag=nginx,severity=info main;'
  notify: reload nginx configs

- name: cofigure nginx to store critical error logs locally
  lineinfile:
      path: /etc/nginx/nginx.conf
      state: present
      regexp: '(error_log /var/log/nginx/error.log);'
      line: '\1 crit;'
      backrefs: yes
  notify: reload nginx configs

- name: cofigure nginx to send all errors to log server
  lineinfile:
      path: /etc/nginx/nginx.conf
      state: present
      insertafter: 'worker_processes auto;'
      line: 'error_log syslog:server={{ server_name }},facility=local6,tag=nginx-error,severity=error;'
  notify: reload nginx configs
...
