galaxy_info:
  author: Maksim Murygin
  description: Role for installing nginx and tuning OS for web server

  license: MIT

  min_ansible_version: 2.0

  platforms:
    - name: CentOS
      versions:
        - 7

  galaxy_tags:
    - networking

dependencies: []
