---
- name: Add records to /etc/hosts
  hosts: all
  become: True
  gather_facts: False
  roles:
    - role: add-entry-to-hosts
      ip: 10.0.10.2
      dns: server
    - role: add-entry-to-hosts
      ip: 10.0.10.3
      dns: client

- name: Configure bacula server
  hosts: server
  become: True
  gather_facts: False
  roles:

- name: Configure bacula client
  hosts: client
  become: True
  gather_facts: False
  roles:
...
