---
- name: install ipa-server dependencies
  yum:
    name:
      - ipa-server
      - ipa-server-dns
      - bind-dyndb-ldap
    state: present

- name: install ipa-server
  command: >
    ipa-server-install -U \
      -r {{ realm }} \
      -n {{ domain }} \
      -p {{ password }} \
      -a {{ password }} \
      --hostname={{ host }} \
      --ip-address={{ host_ip }} \
      --setup-dns \
      --auto-forwarders \
      --no-reverse
...
